# Generated by Django 2.2.2 on 2019-06-28 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190628_2143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_date',
            new_name='created_data',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='slug',
        ),
    ]
